messages:
  start: "👋
👋 Мы рады, что подключились к нашему информационному боту о нашем проекте AI Syndicate. 

 🤗 Получайте информацию о нас в удобном формате. Мы полностью для вас открыты и здесь вы найдете все, что происходит в жизни проекта 

 ↘️ 
❤️‍🔥Жизнь стартапа. Здесь находится все прикольные моменты, отражающие нас и наш проект 
📊 Финансовые показатели. А тут находится наша бизнес-модель
 🐦 Новостная лента. Ежемесячный отчет о развитии нашего проекта + сочные новости о рынке ИИ 

 💀- Не нажимайте!"
keyboard:
  add_profile: "Добавить профиль"
  edit_profile: "Редактировать профиль"
