messages:
  start: "Мы уверены, что наши партнеры и инвестора должны иметь удобный доступ к информации о нашей компании, мы полностью открыты и готовы показывать все что у нас происходит. Нажимая на новостную ленту, вы будете получать дайджест о развитии нашей компании и сферы раз в месяц в первых числах."
keyboard:
  add_profile: "Добавить профиль"
  edit_profile: "Редактировать профиль"
