messages:
  start: "<b>👋 Мы рады, что подключились к нашему информационному боту о нашем проекте AI Syndicate.
\n
🤗 Получайте информацию о нас в удобном формате. Мы полностью для вас открыты и здесь вы найдете все, что происходит в жизни проекта 
\n\n
↘️\n
❤️‍🔥Жизнь стартапа. Здесь находится все прикольные моменты, отражающие нас и наш проект\n
📊 Финансовые показатели. А тут находится наша бизнес-модель\n
🐦 Новостная лента. Ежемесячный отчет о развитии нашего проекта + сочные новости о рынке ИИ 
\n\n

 💀- Не нажимайте!</b>"
keyboard:
  add_profile: "Добавить профиль"
  edit_profile: "Редактировать профиль"
